{"name": "Проверка ошибки создания курьера: создание двух одинаковых курьеров", "status": "passed", "start": 1699380921374, "stop": 1699380921683, "uuid": "d5976551-ab9d-46aa-b7dd-87637c58577e", "historyId": "43e43f114b6fcd00132e12b3d5086de8", "testCaseId": "43e43f114b6fcd00132e12b3d5086de8", "fullName": "tests.test_courier_creation.TestCourierCreation#test_courier_duplicate_courier_failed_create", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_creation"}, {"name": "subSuite", "value": "TestCourierCreation"}, {"name": "host", "value": "WKS-084"}, {"name": "thread", "value": "16844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_creation"}]}